# Zugriff von außen erlauben
allow_anonymous true
listener 1883

# Websockets aktivieren (Wichtig für Browser/Web-Apps)
listener 8080
protocol websockets

# Speicher & Logs (Aus deiner Datei übernommen)
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type subscribe

# Sicherheit
max_connections 10