name: Android CI with Gradle

# Trigger for pushes und merge requests on main and dev
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      # create .env file
      - name: Create .env for BuildConfig
        run: |
          echo "WEBVIEW_URL=${{ vars.WEBVIEW_URL }}" >> .env
          echo "HTTP_ALLOWED_IP=${{ vars.HTTP_ALLOWED_IP }}" >> .env
          echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> .env
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> .env
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> .env
          echo "MQTT_HOST"=${{ secrets.MQTT_HOST }} >> .env
          echo "MQTT_PORT"=${{ secrets.MQTT_PORT }} >> .env
          echo "MQTT_USERNAME"=${{ secrets.MQTT_USERNAME }} >> .env
          echo "MQTT_PASSWORD"=${{ secrets.MQTT_PASSWORD }} >> .env
          echo "DEFAULT_ADMIN_PASSWORD"=${{ secrets.ADMIN_PASSWORD }} >> .env
      
      

      # android specific linting
      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace --build-cache --parallel


      # detekt linter + dokka
      - name: Run Code Analysis
        run: ./gradlew qualityCheck

      - name: Place Dokka files in the assets folder
        if: success()
        run: ./gradlew copyDokkaReports

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Detekt-Report
          path: app/build/reports/detekt/detekt-report.html

      # run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace --build-cache --parallel

      # upload results (on failure)
      - name: Upload Reports (Lint & Tests)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-ci-reports
          path: |
            app/build/reports/tests/testDebugUnitTest/
            app/build/reports/lint-results-debug.html

      - name: Upload Dokka Documentation
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Dokka-Docs
          path: app/build/dokka/html
